# Generated by Django 3.2 on 2022-07-14 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='cust_name',
            field=models.CharField(default='Customer', max_length=100),
            preserve_default=False,
        ),
    ]
