# Generated by Django 3.2 on 2022-07-17 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0002_contact_cust_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='message_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
