# Generated by Django 3.2 on 2022-07-17 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0003_contact_message_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contact',
            options={'ordering': ['-message_date']},
        ),
        migrations.AlterField(
            model_name='contact',
            name='message_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
