# Generated by Django 3.2 on 2022-07-17 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0004_auto_20220717_0950'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='purchase_number',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
    ]
