# Generated by Django 3.2 on 2022-06-05 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseitem',
            name='personalise',
            field=models.TextField(default='None'),
        ),
    ]
