# Generated by Django 3.2 on 2022-06-06 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0003_auto_20220606_0245'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseitem',
            name='customise',
            field=models.TextField(blank=True, null=True),
        ),
    ]
