# Generated by Django 3.2 on 2022-06-06 22:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0004_alter_purchaseitem_customise'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchaseitem',
            name='upload_images',
        ),
    ]
