# Generated by Django 3.2 on 2022-06-23 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0006_auto_20220617_2113'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='delivery_cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
    ]
