# Generated by Django 3.2 on 2022-06-27 13:33

from django.db import migrations, models
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0007_purchase_delivery_cost'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='shp_address_line1',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='purchase',
            name='shp_address_line2',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='purchase',
            name='shp_city',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='purchase',
            name='shp_country',
            field=django_countries.fields.CountryField(default='', max_length=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='purchase',
            name='shp_county',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='purchase',
            name='shp_full_name',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='purchase',
            name='shp_postcode',
            field=models.CharField(default='', max_length=20),
            preserve_default=False,
        ),
    ]
