# Generated by Django 3.2 on 2022-06-27 18:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0008_auto_20220627_1333'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchase',
            name='shipping',
        ),
    ]
