# Generated by Django 3.2 on 2022-06-27 23:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0010_alter_purchaseitem_item_size'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchase',
            name='original_basket',
        ),
        migrations.RemoveField(
            model_name='purchase',
            name='stripe_pid',
        ),
    ]
