# Generated by Django 3.2 on 2022-07-07 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0011_auto_20220627_2353'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='original_basket',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='purchase',
            name='stripe_pid',
            field=models.CharField(default='', max_length=254),
        ),
    ]
