# Generated by Django 3.2 on 2022-07-16 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0013_alter_purchase_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchase',
            name='shp_address_line1',
        ),
        migrations.RemoveField(
            model_name='purchase',
            name='shp_address_line2',
        ),
        migrations.RemoveField(
            model_name='purchase',
            name='shp_city',
        ),
        migrations.RemoveField(
            model_name='purchase',
            name='shp_country',
        ),
        migrations.RemoveField(
            model_name='purchase',
            name='shp_county',
        ),
        migrations.RemoveField(
            model_name='purchase',
            name='shp_full_name',
        ),
        migrations.RemoveField(
            model_name='purchase',
            name='shp_postcode',
        ),
        migrations.AlterField(
            model_name='purchase',
            name='phone',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='postcode',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
