# Generated by Django 3.2 on 2022-07-16 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0014_auto_20220716_2050'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='postcode',
            field=models.CharField(max_length=20),
        ),
    ]
