# Generated by Django 3.2 on 2022-07-17 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0016_alter_purchase_purchase_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase',
            name='purchase_status',
            field=models.CharField(choices=[('new', 'New Order'), ('in_prod', 'In Production'), ('prod_comp', 'Production Complete'), ('despd', 'Despatched')], default='new', max_length=9),
        ),
    ]
