# Generated by Django 3.2 on 2022-07-23 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0020_alter_purchase_purchase_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase',
            name='phone',
            field=models.CharField(max_length=20),
        ),
    ]
