# Generated by Django 3.2 on 2022-07-05 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banner', '0002_alter_banner_info'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banner',
            name='info',
            field=models.TextField(),
        ),
    ]
