# Generated by Django 3.2 on 2022-06-04 20:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('treasures', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='treasure',
        ),
        migrations.AddField(
            model_name='treasure',
            name='image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='treasures.image'),
        ),
    ]
