# Generated by Django 3.2 on 2022-06-05 15:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('treasures', '0002_auto_20220604_2040'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='treasure',
            name='personalise',
        ),
    ]
