# Generated by Django 3.2 on 2022-06-06 00:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('treasures', '0003_remove_treasure_personalise'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='treasure',
            name='image',
        ),
        migrations.AddField(
            model_name='image',
            name='treasure',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='treasures.treasure'),
        ),
    ]
