# Generated by Django 3.2 on 2022-06-06 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('treasures', '0004_auto_20220606_0041'),
    ]

    operations = [
        migrations.AddField(
            model_name='treasure',
            name='customisable',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='treasure',
            name='personalisable',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='treasure',
            name='uploadable_images',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
