# Generated by Django 3.2 on 2022-06-06 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('treasures', '0005_auto_20220606_0245'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(default='no_image', upload_to=''),
        ),
    ]
