# Generated by Django 3.2 on 2022-06-17 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('treasures', '0007_remove_treasure_uploadable_images'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
