# Generated by Django 3.2 on 2022-06-28 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('treasures', '0008_alter_image_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='treasure',
            name='Image_url',
            field=models.URLField(blank=True, max_length=1024, null=True),
        ),
        migrations.AddField(
            model_name='treasure',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
