# Generated by Django 3.2 on 2022-06-28 21:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('treasures', '0009_auto_20220628_1932'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='treasure',
            name='Image_url',
        ),
    ]
